import { sql } from "drizzle-orm";
import { AnyPgColumn, bigint, boolean, index, integer, jsonb, numeric, pgEnum, pgSchema, pgTable, primaryKey, smallint, text, timestamp, unique, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

// Generated by backups/gen_drizzle_schema.py from hikoya_clean.sql + backend_additions.sql.
// Do not edit by hand: change the SQL inputs and regenerate.

const authSchema = pgSchema("auth");

export const ageRating = pgEnum("age_rating", ["0+", "12+", "16+", "18+"]);
export const chapterStatus = pgEnum("chapter_status", ["draft", "published", "pending_review"]);
export const collectionOwnerType = pgEnum("collection_owner_type", ["user", "author", "moderator"]);
export const contentLanguage = pgEnum("content_language", ["ru", "uz"]);
export const likeTargetType = pgEnum("like_target_type", ["story", "chapter", "comment"]);
export const notificationType = pgEnum("notification_type", ["new_comment", "comment_reply", "comment_like", "story_approved", "story_rejected", "chapter_approved", "chapter_rejected", "story_like", "story_hidden", "story_restored", "admin_message"]);
export const readingStatus = pgEnum("reading_status", ["want_to_read", "read", "dropped"]);
export const requestResponseStatus = pgEnum("request_response_status", ["proposed", "accepted", "declined"]);
export const requestStatus = pgEnum("request_status", ["open", "in_progress", "fulfilled", "closed"]);
export const storyProgressStatus = pgEnum("story_progress_status", ["ongoing", "finished", "dropped"]);
export const storyStatus = pgEnum("story_status", ["draft", "published", "unlisted", "pending_review"]);
export const storyTopTier = pgEnum("story_top_tier", ["day", "week", "month"]);
export const storyVisibility = pgEnum("story_visibility", ["public", "unlisted", "draft"]);
export const tagCategory = pgEnum("tag_category", ["genre", "relationship", "warning", "style", "age_rating"]);
export const userRole = pgEnum("user_role", ["reader", "author", "moderator", "admin"]);
export const userStatus = pgEnum("user_status", ["active", "blocked"]);

export const authUsers = authSchema.table("users", {
  instance_id: uuid("instance_id"),
  id: uuid("id").notNull().primaryKey(),
  aud: varchar("aud", { length: 255 }),
  role: varchar("role", { length: 255 }),
  email: varchar("email", { length: 255 }),
  encrypted_password: varchar("encrypted_password", { length: 255 }),
  email_confirmed_at: timestamp("email_confirmed_at", { withTimezone: true }),
  invited_at: timestamp("invited_at", { withTimezone: true }),
  confirmation_token: varchar("confirmation_token", { length: 255 }),
  confirmation_sent_at: timestamp("confirmation_sent_at", { withTimezone: true }),
  recovery_token: varchar("recovery_token", { length: 255 }),
  recovery_sent_at: timestamp("recovery_sent_at", { withTimezone: true }),
  email_change_token_new: varchar("email_change_token_new", { length: 255 }),
  email_change: varchar("email_change", { length: 255 }),
  email_change_sent_at: timestamp("email_change_sent_at", { withTimezone: true }),
  last_sign_in_at: timestamp("last_sign_in_at", { withTimezone: true }),
  raw_app_meta_data: jsonb("raw_app_meta_data"),
  raw_user_meta_data: jsonb("raw_user_meta_data"),
  is_super_admin: boolean("is_super_admin"),
  created_at: timestamp("created_at", { withTimezone: true }),
  updated_at: timestamp("updated_at", { withTimezone: true }),
  phone: text("phone").default(sql`NULL::character varying`),
  phone_confirmed_at: timestamp("phone_confirmed_at", { withTimezone: true }),
  phone_change: text("phone_change").default(sql`''::character varying`),
  phone_change_token: varchar("phone_change_token", { length: 255 }).default(sql`''::character varying`),
  phone_change_sent_at: timestamp("phone_change_sent_at", { withTimezone: true }),
  email_change_token_current: varchar("email_change_token_current", { length: 255 }).default(sql`''::character varying`),
  email_change_confirm_status: smallint("email_change_confirm_status").default(0),
  banned_until: timestamp("banned_until", { withTimezone: true }),
  reauthentication_token: varchar("reauthentication_token", { length: 255 }).default(sql`''::character varying`),
  reauthentication_sent_at: timestamp("reauthentication_sent_at", { withTimezone: true }),
  is_sso_user: boolean("is_sso_user").default(false).notNull(),
  deleted_at: timestamp("deleted_at", { withTimezone: true }),
  is_anonymous: boolean("is_anonymous").default(false).notNull(),
}, (table) => [
  unique("users_phone_key").on(table.phone),
]);

export const authIdentities = authSchema.table("identities", {
  provider_id: text("provider_id").notNull(),
  user_id: uuid("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }),
  identity_data: jsonb("identity_data").notNull(),
  provider: text("provider").notNull(),
  last_sign_in_at: timestamp("last_sign_in_at", { withTimezone: true }),
  created_at: timestamp("created_at", { withTimezone: true }),
  updated_at: timestamp("updated_at", { withTimezone: true }),
  id: uuid("id").defaultRandom().notNull().primaryKey(),
}, (table) => [
  unique("identities_provider_id_provider_unique").on(table.provider_id, table.provider),
]);

export const achievements = pgTable("achievements", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  code: text("code").notNull(),
  title_ru: text("title_ru").notNull(),
  title_uz: text("title_uz").notNull(),
  description_ru: text("description_ru").notNull(),
  description_uz: text("description_uz").notNull(),
  metric: text("metric").notNull(),
  threshold: integer("threshold").notNull(),
}, (table) => [
  unique("achievements_code_key").on(table.code),
]);

export const profiles = pgTable("profiles", {
  id: uuid("id").notNull().primaryKey().references(() => authUsers.id, { onDelete: "cascade" }),
  username: text("username").notNull(),
  display_name: text("display_name").notNull(),
  avatar_url: text("avatar_url"),
  bio: text("bio"),
  role: userRole("role").default("reader").notNull(),
  status: userStatus("status").default("active").notNull(),
  locale_pref: contentLanguage("locale_pref").default("ru").notNull(),
  interests: text("interests").array().default(sql`'{}'::text[]`).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  telegram_id: bigint("telegram_id", { mode: "number" }),
  onboarded_at: timestamp("onboarded_at", { withTimezone: true }),
  is_verified: boolean("is_verified").default(false).notNull(),
  has_password: boolean("has_password").default(false).notNull(),
  instagram_handle: text("instagram_handle"),
  telegram_handle: text("telegram_handle"),
  email: text("email"),
  email_verified: boolean("email_verified").default(false).notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique("profiles_telegram_id_key").on(table.telegram_id),
  unique("profiles_username_key").on(table.username),
  uniqueIndex("profiles_email_key").on(table.email),
]);

export const adminChatMessages = pgTable("admin_chat_messages", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  sender_id: uuid("sender_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  is_admin: boolean("is_admin").notNull(),
  text: text("text").notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("admin_chat_messages_user_id_idx").on(table.user_id, table.created_at),
]);

export const adminChats = pgTable("admin_chats", {
  user_id: uuid("user_id").notNull().primaryKey().references(() => profiles.id, { onDelete: "cascade" }),
  last_message_at: timestamp("last_message_at", { withTimezone: true }).defaultNow().notNull(),
  last_message_preview: text("last_message_preview").default("").notNull(),
  last_sender_is_admin: boolean("last_sender_is_admin").default(false).notNull(),
  unread_by_admin: boolean("unread_by_admin").default(false).notNull(),
  unread_by_user: boolean("unread_by_user").default(false).notNull(),
}, (table) => [
  index("admin_chats_unread_by_admin_idx").on(table.unread_by_admin).where(sql`unread_by_admin`),
]);

export const announcements = pgTable("announcements", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  image_url: text("image_url"),
  text_ru: text("text_ru"),
  text_uz: text("text_uz"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  link_url: text("link_url"),
});

export const stories = pgTable("stories", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  author_id: uuid("author_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  slug: text("slug").notNull(),
  description: text("description").default("").notNull(),
  cover_url: text("cover_url"),
  language: text("language").default("ru").notNull(),
  age_rating: ageRating("age_rating").default("0+").notNull(),
  relationship_type: text("relationship_type"),
  style: text("style"),
  status: storyStatus("status").default("draft").notNull(),
  visibility: storyVisibility("visibility").default("draft").notNull(),
  announce: text("announce"),
  view_count: integer("view_count").default(0).notNull(),
  like_count: integer("like_count").default(0).notNull(),
  comment_count: integer("comment_count").default(0).notNull(),
  bookmark_count: integer("bookmark_count").default(0).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  published_at: timestamp("published_at", { withTimezone: true }),
  rejection_reason: text("rejection_reason"),
  deleted_at: timestamp("deleted_at", { withTimezone: true }),
  chapter_count: integer("chapter_count").default(0).notNull(),
  progress_status: storyProgressStatus("progress_status").default("ongoing").notNull(),
  is_translation: boolean("is_translation").default(false).notNull(),
  genres: text("genres").array().default(sql`'{}'::text[]`).notNull(),
}, (table) => [
  unique("stories_slug_key").on(table.slug),
  index("stories_author_id_idx").on(table.author_id),
  index("stories_deleted_at_idx").on(table.deleted_at).where(sql`(deleted_at IS NOT NULL)`),
  index("stories_genres_idx").using("gin", table.genres),
  index("stories_status_idx").on(table.status).where(sql`(status = 'published'::public.story_status)`),
]);

export const bookmarks = pgTable("bookmarks", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique("bookmarks_user_id_story_id_key").on(table.user_id, table.story_id),
]);

export const chapters = pgTable("chapters", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  order_index: integer("order_index").notNull(),
  title: text("title").notNull(),
  content: text("content").default("").notNull(),
  word_count: integer("word_count").default(0).notNull(),
  status: chapterStatus("status").default("draft").notNull(),
  is_free: boolean("is_free").default(false).notNull(),
  view_count: integer("view_count").default(0).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  published_at: timestamp("published_at", { withTimezone: true }),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  rejection_reason: text("rejection_reason"),
  comment_count: integer("comment_count").default(0).notNull(),
}, (table) => [
  unique("chapters_story_id_order_index_key").on(table.story_id, table.order_index),
  index("chapters_story_id_idx").on(table.story_id),
]);

export const chapterReads = pgTable("chapter_reads", {
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  chapter_id: uuid("chapter_id").notNull().references(() => chapters.id, { onDelete: "cascade" }),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.user_id, table.chapter_id] }),
  index("chapter_reads_user_story_idx").on(table.user_id, table.story_id),
]);

export const collections = pgTable("collections", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  owner_id: uuid("owner_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  owner_type: collectionOwnerType("owner_type").default("user").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  is_featured: boolean("is_featured").default(false).notNull(),
  is_private: boolean("is_private").default(false).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("collections_owner_id_idx").on(table.owner_id),
]);

export const collectionItems = pgTable("collection_items", {
  collection_id: uuid("collection_id").notNull().references(() => collections.id, { onDelete: "cascade" }),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  position: integer("position").default(0).notNull(),
}, (table) => [
  primaryKey({ columns: [table.collection_id, table.story_id] }),
]);

export const comments = pgTable("comments", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  chapter_id: uuid("chapter_id").references(() => chapters.id, { onDelete: "cascade" }),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  parent_id: uuid("parent_id").references((): AnyPgColumn => comments.id, { onDelete: "cascade" }),
  text: text("text").notNull(),
  like_count: integer("like_count").default(0).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  is_spoiler: boolean("is_spoiler").default(false).notNull(),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  hidden_at: timestamp("hidden_at", { withTimezone: true }),
  hidden_by: uuid("hidden_by").references(() => profiles.id, { onDelete: "set null" }),
}, (table) => [
  index("comments_chapter_id_idx").on(table.chapter_id),
  index("comments_story_id_idx").on(table.story_id),
]);

export const customLanguages = pgTable("custom_languages", {
  label: text("label").notNull().primaryKey(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const featuredStories = pgTable("featured_stories", {
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  tier: storyTopTier("tier").notNull(),
  featured_at: timestamp("featured_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.story_id, table.tier] }),
  index("featured_stories_tier_idx").on(table.tier, table.featured_at),
]);

export const follows = pgTable("follows", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  follower_id: uuid("follower_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  author_id: uuid("author_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique("follows_follower_id_author_id_key").on(table.follower_id, table.author_id),
]);

export const heroSlides = pgTable("hero_slides", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  title_ru: text("title_ru"),
  title_uz: text("title_uz"),
  body_ru: text("body_ru"),
  body_uz: text("body_uz"),
  image_url: text("image_url"),
  cta_label_ru: text("cta_label_ru"),
  cta_label_uz: text("cta_label_uz"),
  cta_url: text("cta_url"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  image_url_mobile: text("image_url_mobile"),
});

export const likes = pgTable("likes", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  target_type: likeTargetType("target_type").notNull(),
  target_id: uuid("target_id").notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique("likes_user_id_target_type_target_id_key").on(table.user_id, table.target_type, table.target_id),
]);

export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  actor_id: uuid("actor_id").references(() => profiles.id, { onDelete: "set null" }),
  type: notificationType("type").notNull(),
  story_id: uuid("story_id").references(() => stories.id, { onDelete: "cascade" }),
  chapter_id: uuid("chapter_id").references(() => chapters.id, { onDelete: "cascade" }),
  comment_id: uuid("comment_id").references(() => comments.id, { onDelete: "cascade" }),
  message: text("message"),
  is_read: boolean("is_read").default(false).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("notifications_user_id_idx").on(table.user_id, table.created_at.desc()),
]);

export const platformSettings = pgTable("platform_settings", {
  id: integer("id").default(1).notNull().primaryKey(),
  guest_free_chapters: integer("guest_free_chapters").default(1).notNull(),
  enabled_locales: contentLanguage("enabled_locales").array().default(sql`'{ru,uz}'::public.content_language[]`).notNull(),
  comments_require_approval: boolean("comments_require_approval").default(false).notNull(),
  new_story_requires_review: boolean("new_story_requires_review").default(false).notNull(),
});

export const readingProgress = pgTable("reading_progress", {
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  chapter_id: uuid("chapter_id").notNull().references(() => chapters.id, { onDelete: "cascade" }),
  percent: numeric("percent", { precision: 5, scale: 2 }).default("0").notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.user_id, table.story_id] }),
]);

export const readingStatuses = pgTable("reading_statuses", {
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  status: readingStatus("status").notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.user_id, table.story_id] }),
  index("reading_statuses_user_status_idx").on(table.user_id, table.status),
]);

export const requests = pgTable("requests", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  target_author_id: uuid("target_author_id").references(() => profiles.id, { onDelete: "cascade" }),
  from_user_id: uuid("from_user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  text: text("text").notNull(),
  tags: text("tags").array().default(sql`'{}'::text[]`).notNull(),
  status: requestStatus("status").default("open").notNull(),
  story_id: uuid("story_id").references(() => stories.id, { onDelete: "set null" }),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("requests_target_author_id_idx").on(table.target_author_id),
]);

export const requestResponses = pgTable("request_responses", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  request_id: uuid("request_id").notNull().references(() => requests.id, { onDelete: "cascade" }),
  author_id: uuid("author_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  text: text("text").notNull(),
  status: requestResponseStatus("status").default("proposed").notNull(),
  story_id: uuid("story_id").references(() => stories.id, { onDelete: "set null" }),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("request_responses_request_id_idx").on(table.request_id),
]);

export const savedCollections = pgTable("saved_collections", {
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  collection_id: uuid("collection_id").notNull().references(() => collections.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.user_id, table.collection_id] }),
]);

export const tags = pgTable("tags", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  category: tagCategory("category").notNull(),
  label_ru: text("label_ru").notNull(),
  label_uz: text("label_uz").notNull(),
}, (table) => [
  unique("tags_category_label_ru_key").on(table.category, table.label_ru),
]);

export const storyTags = pgTable("story_tags", {
  story_id: uuid("story_id").notNull().references(() => stories.id, { onDelete: "cascade" }),
  tag_id: uuid("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (table) => [
  primaryKey({ columns: [table.story_id, table.tag_id] }),
]);

export const telegramSupportPendingMessages = pgTable("telegram_support_pending_messages", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  telegram_user_id: bigint("telegram_user_id", { mode: "number" }).notNull(),
  chat_id: bigint("chat_id", { mode: "number" }).notNull(),
  message_id: bigint("message_id", { mode: "number" }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("telegram_support_pending_messages_user_idx").on(table.telegram_user_id),
]);

export const telegramSupportTickets = pgTable("telegram_support_tickets", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  ticket_number: integer("ticket_number").notNull(),
  telegram_user_id: bigint("telegram_user_id", { mode: "number" }).notNull(),
  telegram_username: text("telegram_username"),
  telegram_full_name: text("telegram_full_name"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("telegram_support_tickets_number_idx").on(table.ticket_number),
  index("telegram_support_tickets_user_idx").on(table.telegram_user_id),
]);

export const userAchievements = pgTable("user_achievements", {
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  achievement_id: uuid("achievement_id").notNull().references(() => achievements.id, { onDelete: "cascade" }),
  earned_at: timestamp("earned_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.user_id, table.achievement_id] }),
]);

export const commentReports = pgTable("comment_reports", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  comment_id: uuid("comment_id").notNull().references(() => comments.id, { onDelete: "cascade" }),
  reporter_id: uuid("reporter_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  reason: text("reason").notNull(),
  details: text("details"),
  status: text("status").default("open").notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  resolved_at: timestamp("resolved_at", { withTimezone: true }),
  resolved_by: uuid("resolved_by").references(() => profiles.id, { onDelete: "set null" }),
}, (table) => [
  unique("comment_reports_comment_reporter_key").on(table.comment_id, table.reporter_id),
  index("comment_reports_status_idx").on(table.status, table.created_at),
  index("comment_reports_comment_idx").on(table.comment_id),
]);

export const baAccounts = pgTable("ba_accounts", {
  id: text("id").notNull().primaryKey(),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  provider_id: text("provider_id").notNull(),
  account_id: text("account_id").notNull(),
  password: text("password"),
  access_token: text("access_token"),
  refresh_token: text("refresh_token"),
  id_token: text("id_token"),
  access_token_expires_at: timestamp("access_token_expires_at", { withTimezone: true }),
  refresh_token_expires_at: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique("ba_accounts_provider_account_key").on(table.provider_id, table.account_id),
  index("ba_accounts_user_id_idx").on(table.user_id),
]);

export const baSessions = pgTable("ba_sessions", {
  id: text("id").notNull().primaryKey(),
  user_id: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  token: text("token").notNull(),
  expires_at: timestamp("expires_at", { withTimezone: true }).notNull(),
  ip_address: text("ip_address"),
  user_agent: text("user_agent"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique("ba_sessions_token_key").on(table.token),
  index("ba_sessions_user_id_idx").on(table.user_id),
]);

export const baVerifications = pgTable("ba_verifications", {
  id: text("id").notNull().primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expires_at: timestamp("expires_at", { withTimezone: true }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("ba_verifications_identifier_idx").on(table.identifier),
]);

